In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1.dtype

dtype('int32')

In [6]:
arr1.size

10

In [7]:
len(arr1)

10

In [8]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [9]:
arr1.shape

(10,)

In [10]:
arr1.ndim

1

In [11]:
arr1.sum()

55

In [12]:
arr1.mean()

5.5

In [13]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
arr1Copy = arr1.copy()

In [15]:
arr1Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr1Veiw = arr1.view()
arr1Veiw

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr1[0] = 20

In [18]:
arr1Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr1Veiw

array([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr1[0] = 1

for i in arr1:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [21]:
ones = np.ones((5,5))

In [22]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Numpy random 

In [24]:
random_arr1 = np.random.randint(0 , 10 , size = (2,5))

In [25]:
random_arr1

array([[8, 1, 1, 5, 5],
       [7, 9, 6, 8, 4]])

In [26]:
np.sort(random_arr1)

array([[1, 1, 5, 5, 8],
       [4, 6, 7, 8, 9]])

In [34]:
# range
arrRange = np.arange(0,10,2)

In [35]:
arrRange

array([0, 2, 4, 6, 8])

In [37]:
np.random.shuffle(arrRange)

In [38]:
arrRange

array([2, 8, 0, 6, 4])

In [43]:
arrRangePermutation = np.random.permutation(arrRange)

In [45]:
np.sort(arrRangePermutation)

array([0, 2, 4, 6, 8])

# Numpy Arithmetic Operation

In [67]:
arr1 = np.random.randint(10 , size = (1,5))

In [68]:
arr2 = np.random.randint(10, size = (1,5))

In [71]:
arr1 , arr2

(array([[9, 4, 7, 5, 2]]), array([[2, 9, 7, 9, 3]]))

In [72]:
# add
np.add(arr1 , arr2)

array([[11, 13, 14, 14,  5]])

In [74]:
# sum
arr1 - arr2

array([[ 7, -5,  0, -4, -1]])

In [75]:
# multi
arr1 * arr2

array([[18, 36, 49, 45,  6]])

In [76]:
# divition
arr1 / arr2

array([[4.5       , 0.44444444, 1.        , 0.55555556, 0.66666667]])

In [77]:
# module
np.mod(arr1 , arr2)

array([[1, 4, 0, 5, 2]])

# Numpy comparison operation

In [80]:
# equel to 
arr1[arr1 == 4 ]

array([4])

In [81]:
# not equel to
arr1[arr1 != 4 ]

array([9, 7, 5, 2])

In [82]:
# less than
arr1[ arr1 < 4 ]

array([2])

In [83]:
# less than or equel to
arr1[ arr1 <= 4 ]

array([4, 2])

In [84]:
# greater than
arr1[ arr1 > 5 ]

array([9, 7])

In [85]:
# greater than or equel to
arr1[ arr1 >= 5 ]

array([9, 7, 5])

# Aggregation

`aggregation` performing the same operation on a numberof things

In [46]:
salary = np.array([50,60,70,80,90,100])

In [47]:
salary

array([ 50,  60,  70,  80,  90, 100])

In [48]:
# sum
np.sum(salary)

450

In [49]:
# mean
np.mean(salary)

75.0

In [50]:
# standard deviation
np.std(salary)

17.07825127659933

In [51]:
# variance
np.var(salary)

291.6666666666667

In [53]:
# max
np.max(salary)

100

In [55]:
# min
np.min(salary)

50

In [56]:
# range
range = np.max(salary) - np.min(salary)

In [57]:
range

50