In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1.dtype

dtype('int32')

In [5]:
arr1.size

10

In [6]:
len(arr1)

10

In [7]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [8]:
arr1.shape

(10,)

In [9]:
arr1.ndim

1

In [10]:
arr1.sum()

55

In [11]:
arr1.mean()

5.5

In [14]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
arr1Copy = arr1.copy()

In [20]:
arr1Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr1Veiw = arr1.view()
arr1Veiw

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr1[0] = 20

In [23]:
arr1Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr1Veiw

array([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr1[0] = 1

for i in arr1:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [31]:
ones = np.ones((5,5))

In [32]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
random_arr1 = np.random.randint(0 , 10 , size = (2,5))

In [41]:
random_arr1

array([[5, 2, 0, 5, 5],
       [1, 2, 6, 2, 7]])

In [43]:
np.sort()

None
